version: "3"

services:
  janus:
    container_name: "janus_sv"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/opt/janus/bin/janus", "-F", "/opt/janus/etc/janus"]
    ports:
        - "8088:8088"
        - "8188:8188"
        - "8089:8089"
        - "8189:8189"
        - "7088:7088"
        - "7188:7188"
        - "7089:7089"
        - "7189:7189"
    volumes:
        - ./config:/opt/janus/etc/janus